return {
  enable = true,
  max_lines = 0,
  min_window_height = 0,
  line_numbers = true,
  multiline_threshold = 20,
  trim_scope = "outer",
  mode = "cursor",
  separator = nil,
  zindex = 20,
  on_attach = nil,
  ensure_installed = {
    "bash",
    "lua",
    "c",
    "cpp",
    "python",
    "go",
    "vim",
    "swift",
    "rust",
    "javascript",
    "typescript",
    "markdown",
    "markdown_inline",
    "json",
    "swift",
    "html",
  }
}
